sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t diogomesilva/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=trues diogomesilva/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockerOld"
  env: "Dockerold-env"
  bucket_name: "elasticbeanstalk-us-east-1-160801785813"
  bucket_path: "dockerOld"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY