sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t diogomesilva/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=trues diogomesilva/docker-react npm run test -- --coverage
